###
GET http://localhost:4000/carreras

### Consultar 1 mascota por id
GET http://localhost:4000/carreras/2

### Insertar el registro de un empleado
POST http://localhost:4000/localhost:4000/carreras
Content-Type: application/json

### Editar una carrera
PUT http://localhost:4000/carreras/1
Content-Type: application/json

###Eliminar una carrera (Create Read Update Delete)
DELETE http://localhost:4000/carreras/2









### Consultar una categoria por su id
GET http://localhost:4000/categorias/1

### Consultar todos los empleados
GET http://localhost:4000/categorias

### Insertar el registro de un empleado
POST http://localhost:4000/categorias
Content-Type: application/json

### Editar un empleado
PUT http://localhost:4000/categorias/1
Content-Type: application/json

###Eliminar una carrera (Create Read Update Delete)
DELETE http://localhost:4000/categorias/2





### Consultar un empleado por su id
GET http://localhost:4000/usuarios/1

### Consultar todos los empleados
GET http://localhost:4000/usuarios

### Insertar el registro de un empleado
POST http://localhost:4000/usuarios
Content-Type: application/json

###Eliminar un empleado (Create Read Update Delete)
DELETE http://localhost:4000/usuarios/2

### Editar un empleado
PUT http://localhost:4000/usuarios/1
Content-Type: application/json






### Consultar un lugar por su id
GET http://localhost:4000/lugares/1

### Consultar todos los lugar
GET http://localhost:4000/lugares

### Insertar el registro de un lugar
POST http://localhost:4000/lugares
Content-Type: application/json

###Eliminar un lugar (Create Read Update Delete)
DELETE http://localhost:4000/lugares/2

### Editar un lugar
PUT http://localhost:4000/lugares/1
Content-Type: application/json






### Consultar un comentario por su id
GET http://localhost:4000/comentarios/1

### Consultar todos los comentarios
GET http://localhost:4000/comentarios

### Insertar el registro de un comentario
POST http://localhost:4000/comentarios
Content-Type: application/json

###Eliminar un comentario (Create Read Update Delete)
DELETE http://localhost:4000/comnetarios/2

### Editar un comentario
PUT http://localhost:4000/comentarios/1
Content-Type: application/json

