###
GET http://localhost:4000/carreras

### Consutar todas las mascotas
GET http://localhost:4000/carreras

### Consultar 1 mascota por id
GET http://localhost:4000/carreras/2






### Enviar un saludo
GET http://localhost:4000/categorias/saludo

### Consultar una categoria por su id
GET http://localhost:4000/categorias/1

### Consultar todos los empleados
GET http://localhost:4000/categorias

### Insertar el registro de un empleado
POST http://localhost:4000/categorias
Content-Type: application/json


### Editar un empleado
PUT http://localhost:4000/categorias/1
Content-Type: application/json



### Enviar un saludo
GET http://localhost:4000/usuarios/saludo

### Consultar un empleado por su id
GET http://localhost:4000/usuarios/1

### Consultar todos los empleados
GET http://localhost:4000/usuarios

### Insertar el registro de un empleado
POST http://localhost:4000/usuarios
Content-Type: application/json


###Eliminar un empleado (Create Read Update Delete)
DELETE http://localhost:4000/usuarios/2

### Editar un empleado
PUT http://localhost:4000/usuarios/1
Content-Type: application/json



### Enviar un lugar
GET http://localhost:4000/lugares/saludo

### Consultar un lugar por su id
GET http://localhost:4000/lugares/1

### Consultar todos los lugar
GET http://localhost:4000/lugares

### Insertar el registro de un lugar
POST http://localhost:4000/lugares
Content-Type: application/json


###Eliminar un lugar (Create Read Update Delete)
DELETE http://localhost:4000/lugares/2

### Editar un lugar
PUT http://localhost:4000/lugares/1
Content-Type: application/json






### Enviar un saludo
GET http://localhost:4000/comentarios/saludo

### Consultar un empleado por su id
GET http://localhost:4000/comentarios/1

### Consultar todos los empleados
GET http://localhost:4000/comentarios

### Insertar el registro de un empleado
POST http://localhost:4000/comentarios
Content-Type: application/json


###Eliminar un empleado (Create Read Update Delete)
DELETE http://localhost:4000/comnetarios/2

### Editar un empleado
PUT http://localhost:4000/comentarios/1
Content-Type: application/json

